/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthedDispatchRulesIndexRouteImport } from './routes/_authed/dispatch-rules/index'
import { Route as AuthedEgressIndexRouteImport } from './routes/_authed/egress/index'
import { Route as AuthedRoomsIndexRouteImport } from './routes/_authed/rooms/index'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedTrunksIndexRouteImport } from './routes/_authed/trunks/index'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDispatchRulesIndexRoute =
  AuthedDispatchRulesIndexRouteImport.update({
    id: '/dispatch-rules/',
    path: '/dispatch-rules/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedEgressIndexRoute = AuthedEgressIndexRouteImport.update({
  id: '/egress/',
  path: '/egress/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRoomsIndexRoute = AuthedRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTrunksIndexRoute = AuthedTrunksIndexRouteImport.update({
  id: '/trunks/',
  path: '/trunks/',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/dispatch-rules/': typeof AuthedDispatchRulesIndexRoute
  '/egress/': typeof AuthedEgressIndexRoute
  '/rooms/': typeof AuthedRoomsIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
  '/trunks/': typeof AuthedTrunksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginIndexRoute
  '/dispatch-rules': typeof AuthedDispatchRulesIndexRoute
  '/egress': typeof AuthedEgressIndexRoute
  '/rooms': typeof AuthedRoomsIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/trunks': typeof AuthedTrunksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/': typeof AuthedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_authed/dispatch-rules/': typeof AuthedDispatchRulesIndexRoute
  '/_authed/egress/': typeof AuthedEgressIndexRoute
  '/_authed/rooms/': typeof AuthedRoomsIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
  '/_authed/trunks/': typeof AuthedTrunksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/'
    | '/dispatch-rules/'
    | '/egress/'
    | '/rooms/'
    | '/settings/'
    | '/trunks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dispatch-rules'
    | '/egress'
    | '/rooms'
    | '/settings'
    | '/trunks'
  id:
    | '__root__'
    | '/_authed'
    | '/_authed/'
    | '/login/'
    | '/_authed/dispatch-rules/'
    | '/_authed/egress/'
    | '/_authed/rooms/'
    | '/_authed/settings/'
    | '/_authed/trunks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dispatch-rules/': {
      id: '/_authed/dispatch-rules/'
      path: '/dispatch-rules'
      fullPath: '/dispatch-rules/'
      preLoaderRoute: typeof AuthedDispatchRulesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/egress/': {
      id: '/_authed/egress/'
      path: '/egress'
      fullPath: '/egress/'
      preLoaderRoute: typeof AuthedEgressIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/rooms/': {
      id: '/_authed/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof AuthedRoomsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/trunks/': {
      id: '/_authed/trunks/'
      path: '/trunks'
      fullPath: '/trunks/'
      preLoaderRoute: typeof AuthedTrunksIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedDispatchRulesIndexRoute: typeof AuthedDispatchRulesIndexRoute
  AuthedEgressIndexRoute: typeof AuthedEgressIndexRoute
  AuthedRoomsIndexRoute: typeof AuthedRoomsIndexRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
  AuthedTrunksIndexRoute: typeof AuthedTrunksIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedDispatchRulesIndexRoute: AuthedDispatchRulesIndexRoute,
  AuthedEgressIndexRoute: AuthedEgressIndexRoute,
  AuthedRoomsIndexRoute: AuthedRoomsIndexRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
  AuthedTrunksIndexRoute: AuthedTrunksIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
